filebeat:
  image: bargenson/filebeat:latest
  restart: unless-stopped
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock
  environment:
   - LOGSTASH_HOST=192.168.88.132
   - LOGSTASH_PORT=5044
   - SHIPPER_NAME=aWonderfulName
